server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.2.113.221:3306/springboot_demo
    username: root
    password: 20000421Ai
  mvc:
    view:
      suffix: .html
      prefix: /
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
